### ISSUE TITLE
java.lang.NoSuchMethodError: sbt.UpdateConfiguration.copy$default$1()Lscala/Option

### ISSUE THREAD

**Issue by LantaoJin** [databricks/sbt-spark-package#51]
v0.2.6

sbt package

```
java.lang.NoSuchMethodError: sbt.UpdateConfiguration.copy$default$1()Lscala/Option;
	at sbt.dependencygraph.DependencyGraphSbtCompat$Implicits$RichUpdateConfiguration$.withMissingOk$extension(DependencyGraphSbtCompat.scala:12)
	at net.virtualvoid.sbt.graph.DependencyGraphSettings$$anonfun$baseSettings$3.apply(DependencyGraphSettings.scala:40)
	at net.virtualvoid.sbt.graph.DependencyGraphSettings$$anonfun$baseSettings$3.apply(DependencyGraphSettings.scala:40)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoSuchMethodError: sbt.UpdateConfiguration.copy$default$1()Lscala/Option;
```

**Comment by nightscape** [comment]
@LantaoJin, to save you some hazzle: Just don't use this project. It hasn't been updated in years and one can easily work without it.
I just removed it from my project yesterday: https://github.com/crealytics/spark-excel/pull/370/files
