### ISSUE TITLE
Unable to resolve dependency "org.spark-packages" % "sbt-spark-package" % "0.2.2"

### ISSUE THREAD

**Issue by ryan-williams** [databricks/sbt-spark-package#9]
Hi there, I must be doing something pretty dumb because I can't get SBT to find this repo's JAR for use as a plugin.

Check out [the `sp` branch of hammerlab/spark-json-relay](https://github.com/hammerlab/spark-json-relay/tree/sp).

I have [a working build.sbt](https://github.com/hammerlab/spark-json-relay/blob/sp/build.sbt) there, and [your suggested `addSbtPlugin` line in project/plugins.sbt](https://github.com/hammerlab/spark-json-relay/blob/sp/project/plugins.sbt).

When I run `sbt`, I get:

```
[info] Loading project definition from /Users/ryan/c/spree/json-relay/project
[info] Updating {file:/Users/ryan/c/spree/json-relay/project/}json-relay-build...
[info] Resolving org.spark-packages#sbt-spark-package;0.2.2 ...
[warn] 	module not found: org.spark-packages#sbt-spark-package;0.2.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/ryan/.ivy2/local/org.spark-packages/sbt-spark-package/scala_2.10/sbt_0.13/0.2.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/spark-packages/sbt-spark-package_2.10_0.13/0.2.2/sbt-spark-package-0.2.2.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.spark-packages#sbt-spark-package;0.2.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.spark-packages:sbt-spark-package:0.2.2 (sbtVersion=0.13, scalaVersion=2.10)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.spark-packages:sbt-spark-package:0.2.2 (sbtVersion=0.13, scalaVersion=2.10) (/Users/ryan/c/spree/json-relay/project/plugins.sbt#L1-2)
[warn] 		  +- default:json-relay-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: org.spark-packages#sbt-spark-package;0.2.2: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.spark-packages#sbt-spark-package;0.2.2: not found
```

This basic error happens with {SBT 0.12, SBT 013} x {Scala 2.10, Scala 2.11}. I don't see a JAR published in any of the Maven repos I looked for it in. What am I missing? Thanks.

**Comment by gustavonalle** [comment]
Adding:
``` resolvers += Resolver.url("bintray-spark-packages", url("http://dl.bintray.com/spark-packages/maven/"))(Resolver.ivyStylePatterns) ```

to my  ```plugins.sbt``` file solved the issue

**Comment by saurfang** [comment]
For me, I had to do this instead:
`resolvers += "bintray-spark-packages" at "https://dl.bintray.com/spark-packages/maven/"`

**Comment by brkyvz** [comment]
There unfortunately is a mismatch between sbt's expected plugin directory resolution vs. maven's. Adding `resolvers += "bintray-spark-packages" at "https://dl.bintray.com/spark-packages/maven/"` to `project/plugins.sbt` should solve this issue.

**Comment by rpuch** [comment]
According to https://spark.apache.org/news/new-repository-service.html , we should not use dl.bintray anymore. I replaced the following

```
resolvers += "bintray-spark-packages" at "https://dl.bintray.com/spark-packages/maven/"
```

with this

```
resolvers += "spark-packages" at "https://repos.spark-packages.org/"
```

and it seems to work now.
